name:                Miku
version:             0.1.0.0
github:              "IAmParad0x/Miku"
license:             MIT
author:              "IAmParadox"
maintainer:          "confusedstudent13@gmail.com"
copyright:           "2022 IAmParadox"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/IAmParad0x/Mikur#readme>

default-extensions:
- AllowAmbiguousTypes
- DataKinds
- DerivingStrategies
- OverloadedStrings
- ImportQualifiedPost
- LambdaCase
- NoImplicitPrelude
- RankNTypes
- RecordWildCards
- TupleSections
- TypeApplications
- KindSignatures
- ScopedTypeVariables
- GADTs
- TemplateHaskell
- TypeOperators
- MultiParamTypeClasses
- PolyKinds              
- FlexibleInstances
- TypeFamilies

ghc-options:
  -Wall

library:
  source-dirs: src
  exposed-modules:
  - Miku
  dependencies:
  - base >= 4.7 && < 5
  - brick >= 0.69
  - containers
  - data-default
  - directory
  - filepath
  - lens
  - megaparsec
  - mtl
  - relude
  - text
  - time
  - transformers
  - vty >= 5.35.1

executables:
  miku:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -O2
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >= 4.7 && < 5
    - Miku
    - relude

tests:
  timeTracker-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >= 4.7 && < 5
    - Miku
    - relude
