name:                timeTracker
version:             0.1.0.0
github:              "githubuser/timeTracker"
license:             MIT
author:              "IAmParadox"
maintainer:          "confusedstudent13@gmail.com"
copyright:           "2022 IAmParadox"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/timeTracker#readme>

dependencies:
- base >= 4.7 && < 5
- brick
- text
- lens
- time
- transformers
- mtl

library:
  source-dirs: src

executables:
  timeTracker-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - timeTracker

tests:
  timeTracker-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - timeTracker
